version: '3.6'

services:
  postgres:
    container_name: cf-poc-tunnel-postgres
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cf-poc-tunnel